{% set name = "kaldiio" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nttcslab-sp/kaldiio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91f41fad47be88d7435c11a28d8c619d89063f5435ec46eeb6ada26d9f5540c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - kaldiio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nttcslab-sp/kaldiio
  summary: Kaldi-ark loading and writing module
  description: |
    kaldiio is an IO utility implemented in pure Python language for several file formats used in kaldi, which are named asark and scp. ark and scp are used in in order to archive some objects defined in Kaldi, typically it is Matrix object of Kaldi.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
